#!/bin/bash

# Disable Root Login
sed -i -e 's@PermitRootLogin yes@#PermitRootLogin yes@g' /etc/sshd_config

# Restart SSH Service
launchctl unload /Library/LaunchDaemons/com.openssh.sshd.plist
launchctl load /Library/LaunchDaemons/com.openssh.sshd.plist
