#!/bin/bash

# Enable Root Login
sed -i -e 's/#PermitRootLogin yes/PermitRootLogin yes/g' /private/etc/ssh/sshd_config

# Restart SSH Service
launchctl unload /Library/LaunchDaemons/com.openssh.sshd.plist
launchctl load /Library/LaunchDaemons/com.openssh.sshd.plist
