#!/bin/bash

# Remove Bonjour Announcement
plutil -key Sockets -key Listeners -key Bonjour -remove /Library/LaunchDaemons/com.openssh.sshd.plist

# Restart SSH Service
launchctl unload /Library/LaunchDaemons/com.openssh.sshd.plist
launchctl load /Library/LaunchDaemons/com.openssh.sshd.plist